baseURL = "https://hengshi.me"
languageCode = "en-us"
title = "-behaviour(human)."
theme = "solar-theme-hugo"

[pagination]
  pagerSize = 5

hasCJKLanguage = true

copyright = "This work is licensed under Creative Commons BY-NC-SA & Apache License."

[services]
  [services.googleAnalytics]
    id = "G-MB47BM2S51"

[markup]
  [markup.highlight]
    codeFences = true
    style = "solarized-dark256"

[author]
  name = "Heng Shi"

[permalinks]
  post = "/post/:title/"

[params]
  scheme = "gray"
  description = "Learning by Doing"
  since = 2015
  footer = "Icons made by <a href=\"https://www.freepik.com/\" title=\"Freepik\">Freepik</a> from <a href=\"https://www.flaticon.com/\" title=\"Flaticon\">Flaticon</a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\" title=\"Creative Commons BY 3.0\" target=\"_blank\">CC 3.0 BY</a>"
  utterances = "wilburpolarlight/blog-hugo-comments"
  pageNotFoundTitle = "404 - Page not found"
  linkedin = "hengshi"
  github = "wilburpolarlight"
  email = "hshi.usask@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 30

  [[menu.other]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.other]]
    name = "License"
    url = "/license/"
    weight = 20